name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

env:
  REGISTRY: docker.io
  IMAGE_NAME: ihmily/comfyui-full

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ inputs.version }}
          type=raw,value=latest
          type=raw,value=gpu-cu124

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ inputs.version }}
        release_name: Release ${{ inputs.version }}
        body: |
          ## ComfyUI Docker Image Release ${{ inputs.version }}
          
          ### What's New
          - Updated ComfyUI with latest custom nodes
          - CUDA 12.4 support
          - Pre-installed popular custom nodes
          
          ### Docker Image
          ```bash
          docker pull ihmily/comfyui-full:gpu-cu124
          docker pull ihmily/comfyui-full:latest
          docker pull ihmily/comfyui-full:${{ inputs.version }}
          ```
          
          ### Usage
          ```bash
          docker run -d \
            --name comfyui \
            --gpus all \
            -p 8188:8188 \
            -e CUDA_DEVICE=0 \
            ihmily/comfyui-full:gpu-cu124
          ```
        draft: false
        prerelease: false
